@startuml





/' Objects '/

namespace Presentation {
	class CreateGroupPanel {
		+CreateGroupPanel(Business::CoordinateGroupManager* gm, Business::CoordinateConverter* cc)
		+~CreateGroupPanel()
		-coordinateConverter : Business::CoordinateConverter*
		-groupManager : Business::CoordinateGroupManager*
		+createCartesianGroup(const std::string& label, float x, float y) : void
		+createPolarGroup(const std::string& label, float r, float theta) : void
	}

	class MainWindow {
		+MainWindow(Business::CoordinateGroupManager* gm, Business::DataRetriever* dr, Business::CoordinateConverter* cc)
		+~MainWindow()
		-coordinateConverter : Business::CoordinateConverter*
		-groupManager : Business::CoordinateGroupManager*
		-dataRetriever : Business::DataRetriever*
		+displayAllGroups() : void
		+displayGroupsByLabel(const std::string& label) : void
		+showCreatePanel() : void
		+showModifyPanel() : void
	}

	class ModifyGroupPanel {
		+ModifyGroupPanel(Business::CoordinateGroupManager* gm, Business::DataRetriever* dr, Business::CoordinateConverter* cc)
		+~ModifyGroupPanel()
		-coordinateConverter : Business::CoordinateConverter*
		-groupManager : Business::CoordinateGroupManager*
		-dataRetriever : Business::DataRetriever*
		+updateGroup(int id, const std::string& label, float x, float y) : void
		+updateGroup(int id, const std::string& label, float r, float theta) : void
	}

	class SearchPanel {
		+SearchPanel(Business::DataRetriever* dr)
		+~SearchPanel()
		-dataRetriever : Business::DataRetriever*
		+search(const std::string& label) : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+viewAll() : std::vector<std::tuple<int , std::string , float , float , float , float>>
	}
}


namespace Data {
	class CartesianCoordinates {
		+CartesianCoordinates(float newX, float newY)
		+~CartesianCoordinates()
		+getX() : float {query}
		+getY() : float {query}
		-x : float
		-y : float
		+setX(float newX) : void
		+setY(float newY) : void
	}

	class CoordinateGroupDAO {
		+CoordinateGroupDAO(Data::DatabaseConnection* conn)
		+~CoordinateGroupDAO()
		-dbConnection : Data::DatabaseConnection*
		+findAll() : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+findByLabel(const std::string& label) : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+remove(int id) : void
		+save(const std::string& label, float x, float y, float r, float theta) : void
		+update(int id, const std::string& label, float x, float y, float r, float theta) : void
	}

	class DatabaseConnection {
		+DatabaseConnection(const std::string& connStr, int p, const std::string& u, const std::string& pw)
		+~DatabaseConnection()
		-port : int
		-connectionString : std::string
		-password : std::string
		-username : std::string
		+connect() : void
		+disconnect() : void
	}

	class PolarCoordinates {
		+PolarCoordinates(float newR, float newTheta)
		+~PolarCoordinates()
		+getR() : float {query}
		+getTheta() : float {query}
		-r : float
		-theta : float
		+setR(float newR) : void
		+setTheta(float newTheta) : void
	}
}


namespace Business {
	class CoordinateConverter {
		+{static} cartesianToPolar(float x, float y) : std::pair<float , float>
		+{static} polarToCartesian(float r, float theta) : std::pair<float , float>
	}

	class CoordinateGroupManager {
		+CoordinateGroupManager(Data::CoordinateGroupDAO* dao)
		+~CoordinateGroupManager()
		-coordinateGroupDAO : Data::CoordinateGroupDAO*
		+getAllGroups() : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+searchGroups(const std::string& label) : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+createGroup(const std::string& label, float x, float y) : void
		+createGroup(const std::string& label, float r, float theta) : void
		+deleteGroup(int id) : void
		+updateGroup(int id, const std::string& label, float x, float y) : void
		+updateGroup(int id, const std::string& label, float r, float theta) : void
	}

	class DataRetriever {
		+DataRetriever(Data::CoordinateGroupDAO* dao)
		+~DataRetriever()
		-coordinateGroupDAO : Data::CoordinateGroupDAO*
		+retrieveAllGroups() : std::vector<std::tuple<int , std::string , float , float , float , float>>
		+retrieveByLabel(const std::string& label) : std::vector<std::tuple<int , std::string , float , float , float , float>>
	}
}





/' Inheritance relationships '/




/' Aggregation relationships '/

Data.CoordinateGroupDAO o-- Data.DatabaseConnection


Business.CoordinateGroupManager o-- Data.CoordinateGroupDAO


Presentation.CreateGroupPanel o-- Business.CoordinateConverter


Presentation.CreateGroupPanel o-- Business.CoordinateGroupManager


Business.DataRetriever o-- Data.CoordinateGroupDAO


Presentation.MainWindow o-- Business.CoordinateConverter


Presentation.MainWindow o-- Business.CoordinateGroupManager


Presentation.MainWindow o-- Business.DataRetriever


Presentation.ModifyGroupPanel o-- Business.CoordinateConverter


Presentation.ModifyGroupPanel o-- Business.CoordinateGroupManager


Presentation.ModifyGroupPanel o-- Business.DataRetriever


Presentation.SearchPanel o-- Business.DataRetriever






/' Dependency relationships '/

Business.CoordinateConverter <.. Presentation.CreateGroupPanel


Business.CoordinateConverter <.. Presentation.MainWindow


Business.CoordinateConverter <.. Presentation.ModifyGroupPanel


Data.CoordinateGroupDAO <.. Business.CoordinateGroupManager


Data.CoordinateGroupDAO <.. Business.DataRetriever


Business.CoordinateGroupManager <.. Presentation.CreateGroupPanel


Business.CoordinateGroupManager <.. Presentation.MainWindow


Business.CoordinateGroupManager <.. Presentation.ModifyGroupPanel


Business.DataRetriever <.. Presentation.MainWindow


Business.DataRetriever <.. Presentation.ModifyGroupPanel


Business.DataRetriever <.. Presentation.SearchPanel


Data.DatabaseConnection <.. Data.CoordinateGroupDAO






/' Nested objects '/



@enduml
